apiVersion: v1
kind: Secret
metadata:
  name: annexturec-secrets
  namespace: annexture-c-webapp
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzLmtiZ3dnanh2anFzZnBvcWdieHJqOktoJTQwblN1Zml5YW5AYXdzLTAtYXAtbm9ydGhlYXN0LTEucG9vbGVyLnN1cGFiYXNlLmNvbTo1NDMyL3Bvc3RncmVzCg==
  PORT: NTAwMAo=
  JWT_SECRET: eUFTU0VUX01BTkFHRU1FTlRfSldUX1RPS0VOX0AkCg==